// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
	Done   *bool  `json:"done"`
}

type User struct {
	ID       string `json:"id"`
	Username string `json:"username"`
}
